### ISSUE TITLE
Dead and ugly links 

### ISSUE THREAD

**Issue by butler54** [IBM-Bluemix-Docs/MDMOnCloud#1]
This link on the readme page is dead:
http://ibmtvdemo.edgesuite.net/software/analytics/learning-centers/mdm-on-cloud/index.html

This link ()https://public.dhe.ibm.com/cloud/bluemix/hosted/ send users to a index page where it is not clear what documentation (and versions) are relevant. 
- Direct links would be a suggested fix (or links at least to the latest version of each relevant docs).

**Comment by arkadianriver** [comment]
Thanks for the dead link; it's gone.

Intend to keep linking to the download site, though. The PDFs are updated and uploaded regularly with each version, but for the hosted services products, these IBM Cloud doc landing pages merely serve as a reference and aren't otherwise maintained. When someone orders a hosted service at a particular version level, the welcome letter received should indicate which PDF version applies to the product ordered.

I have added a link to the ibm.com page for the product, however, and hopefully it can help those who land on this page and want more specifics about the product.
